excerpt_separator: ""
markdown: kramdown
url: http://liuzhongshu.github.io
title: 程序人生
tagline: A log of my life
description: liuzhongshu
paginate: 1
disqus_shortname: liuzhongshu
permalink: /:title/
